name: kaze
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.5
  launcher_assist: ^1.1.3
  image_picker: ^0.7.5
  firebase_core: ^1.2.0
  firebase_analytics: ^8.1.0
  firebase_auth: ^1.2.0
  firebase_storage: ^8.1.0
  google_sign_in: ^5.0.3
  palette_generator: ^0.3.0
  path: ^1.8.0
  path_provider: ^2.0.1
  flutter_switch: ^0.3.1
  notification_permissions: ^0.4.8
  intent: ^1.4.0
  flutter_dnd: ^0.1.3
  flutter_local_notifications: ^6.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/focus.png
    - assets/time.png
    - assets/shutdown.png
    - assets/category.png
    - assets/backup.png
    - assets/danger.png
    - assets/notification.png
    - assets/phone.png
    - assets/watch.png
    - assets/done.png
    - assets/wait.png
    - assets/dnd.jpeg
    - assets/add.png
    - assets/loading.png

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/product_sans.ttf

